pipeline {
    agent { node { label 'AGENT-1' } }
    
    options {
        ansiColor('xterm')
    }

    stages {
        stage('Init'){
            steps {
                sh'''
                    cd 01-vpc
                    ls -ltr
                    pwd
                    terraform init
                '''
            }
        }
    }
}